### PR TITLE
Feature : Number converter

### PR DESCRIPTION
**Pull request by jccharlemagne**
Feature : Add number convert on import reference entities

### CODE REVIEW

**Comment by jjanvier** [comment]
@SamirBoulil possible to merge? :heart:

**Comment by SamirBoulil** [comment]
Hi @jccharlemagne and thank you for your contribution, I see we miss a small unit test (spec) before merging your PR. Feel free to add it (or I'll try to find some time to add it myself ;))

**Comment by jjanvier** [comment]
@SamirBoulil tests ajoutés ;)

**Comment by jjanvier** [comment]
I don't understand why the build fails on composer install as we didn't change the .lock

**Comment by jjanvier** [comment]
Guys, do you have any news about why the build fails?
cc @SamirBoulil @juliensnz

**Comment by SamirBoulil** [comment]
@jjanvier I'll have a look at it Chef JJ

**Review by SamirBoulil — APPROVED** [review]

**Comment by jjanvier** [comment]
@SamirBoulil thanks for the approval but is it mergeable or not?

**Comment by SamirBoulil** [comment]
yes now that the CI passes, it is :)

**Pull request merged**
